version: '3.8'

services:
  tomcat-server:
    build: .
    container_name: tomcat-network-services
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
      - ./logs:/usr/local/tomcat/logs
      - ./conf:/usr/local/tomcat/conf
  
    environment:
      - TZ=America/Sao_Paulo