version: '3.8'

services:
  tomcat-server:
    build: .
    container_name: tomcat-network-services
    ports:
      - "8080:8080"
      - "8443:8443"
    # volumes:
    #   - ./webapps:/opt/tomcat/webapps
    #   - ./logs:/opt/tomcat/logs
    #   - ./conf:/opt/tomcat/conf
    environment:
      - TZ=America/Sao_Paulo